name: Sync Leetcode

on:
  workflow_dispatch:

  schedule:
    - cron: "30 6 * * *"
    - cron: "30 18 * * *"

jobs:
  build:
    runs-on: ubuntu-lates

    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true
          commit-header: "[LeetCode Sync]"
